import type { Metadata } from "next";
import "./globals.css";
import { MagicLinkManager } from "@/components/common";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				{children}
				<MagicLinkManager />
			</body>
		</html>
	);
}
