import type { Metadata } from "next";
import "./globals.css";
import { AuthManager } from "@/components/common";
import { ThemeProvider } from "@/components/providers";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<ThemeProvider>
					<AuthManager />
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
